# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IN_NOTEBOOK": "00_core.ipynb",
         "get_issues": "00_core.ipynb",
         "issue2txt": "00_core.ipynb",
         "issue2markdown": "00_core.ipynb",
         "issue2ipynb": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://josiahls.github.io/ghissue2docs/"

git_url = "https://github.com/josiahls/ghissue2docs/tree/main/"

def custom_doc_links(name): return None
